Consolidate write_travel_diary
arup-group/pam pull request #106
Opened 2021-09-21 15:46 UTC by JosePazNoguera

The write_travel_diary method is basically a copy of the to_csv method.
This commit removes the redundant code. I have compared test_8_write.dy results and they look exactly the same.

2021-09-21 20:38 UTC, mfitz approved these changes
I love it - delete is the best refactoring!

Can we delete the commented out code though?

2021-09-29 15:15 UTC, JosePazNoguera commented
Commit ae8d1a7 builds on the work @mfitz did. Apart from renaming the two tests, it looks at the legs.csv file not the activities.csv file. 
The first test checks whether the file exists. The second test compares the content of legs.csv (created by the to_csv method) against the output created by the master branch (using the previous user-defined method). The test fails because the order of the columns has changed, there are a couple extra columns and the formatting of the time is different when you use the to_csv method.

2021-09-29 16:06 UTC, fredshone requested changes
there are some lingering `>>>>>>>>>` etc which are causing tests to fail

2021-09-29 16:06 UTC, fredshone commented on pam/write.py
>      if attributes_path:
remove attributes path option altogther, the `to_csv` function will output attributes in any case

2021-09-29 16:06 UTC, fredshone commented on pam/write.py
> +                        'hzone': hh.location.area,
good

2021-09-29 16:06 UTC, fredshone commented on tests/test_8_write.py
> +<<<<<<< HEAD
remove these `<<<<<<<<<`

2021-09-29 16:06 UTC, fredshone commented on tests/test_8_write.py
> +<<<<<<< HEAD
etc

2021-09-29 16:26 UTC, JosePazNoguera commented
Apologies for the V2 and V3 commits. I didn't realize a small typo and then created a merge conflict .... 
Just ignore them. The relevant commit is the latest one "Fixed Typo"

2021-09-29 16:31 UTC, JosePazNoguera commented on pam/write.py
>      if attributes_path:
OK

2021-09-29 17:50 UTC, fredshone commented
Great effort - I've made some changes that I'd like you do consider

1. removed `write_travel_diary` entirely - I noticed it was not in use in any of the examples - if someone complains we can revert but i think this will be fine as the required funcionality is in `to_csv`.
2. removed the hh.location.area field from the legs outputs - this information was duplicated in the hh output
3. fixed tests to suit
4. i refactored the `write_population_csv` to use the `to_csv` logic. Any changes for future improvements are all in one place now. I also renamed to `write_population_csvs`. I also confirmed this was not in use in the examples and I fixed (deleted) the required tests for a slight loss in coverage that we can address in future
5. Some minor formatting

2021-09-30 08:14 UTC, fredshone approved these changes

2021-09-30 11:37 UTC, merged