Fix scoring
arup-group/pam pull request #133
Opened 2022-03-29 11:38 UTC by Theodore-Chatziioannou

Fixes some bugs of the PAM scoring module, validating them against MATSim output scores (from the "experienced plans" xml file).

Changes:
- the utility calculation for small durations is brought in line with the MATSim code [here](https://github.com/matsim-org/matsim-libs/blob/77536f9f05ff70b69bdf54f19604f5732d81949c/matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelActivityScoring.java#L151-L193)
- fixed the "number of PT interchanges" calculation
- activity wrapping is only happening if the first and last activity are of the same type (see [here](https://github.com/matsim-org/matsim-libs/blob/77536f9f05ff70b69bdf54f19604f5732d81949c/matsim/src/main/java/org/matsim/core/scoring/functions/CharyparNagelActivityScoring.java#L241-L265)).
- boarding times can now be read from the experienced plans, enabling the calculation of waiting time disutilities
- waiting time (if any) is subtracted from the leg travel time
- conversion from `timedelta` to `hours` is done by dividing by a timedelta object (previously, `.seconds` were extracted, dropping any `day` elements, and resulting -for example- in erroneous activity duration for 24-hr activities).
- tests check the results against the MATSim-calculated scores of a Londinium sim
- PAM Plans now have a `.score` property, which gets populated with MATSim scores when reading experienced plans.

Next steps:
- align the scoring config format with the MC output json file, for easier interface between the two
- add some plan utility plots

2022-03-29 12:10 UTC, Theodore-Chatziioannou commented
**fit against MATSim scores**

before:
![scoring_before](https://user-images.githubusercontent.com/60702999/160608244-1752ab5e-4f66-4eb5-b75f-974225f478c9.png)

after:
![scoring_after_v4](https://user-images.githubusercontent.com/60702999/160608258-e2b100ac-d33a-4afb-8afc-5af286385291.png)

2022-03-29 13:13 UTC, ana-kop approved these changes
great improvements @Theodore-Chatziioannou , looks like significant move closer to MATSIM's scoring!

2022-03-29 13:13 UTC, ana-kop commented on pam/scoring.py
> +        if not activities[0].act == activities[-1].act:
very minor but I would just write 

`if activities[0].act != activities[-1].act:`

2022-03-29 13:13 UTC, ana-kop commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
Why are we subtracting 1 from `in_transit` rather than just keeping it as it was?

2022-03-29 13:14 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +        if not activities[0].act == activities[-1].act:
good point

2022-03-29 13:15 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
so that the first PT vehicle boarding of each trip is not counted as a line switch.

2022-03-29 14:01 UTC, fredshone requested changes

2022-03-29 16:30 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
🤦🏻 I forgot about the walking. We havn't gone mad after all.

As things stand I belive we can take the number of pt interactions for a trip and subtract 2? As the start and end legs with always be access/egress interactions? However, that brings us close to the og implementation I think:

```
transits = []
in_transit = 0
for activity in plan.activities:
    if activity is a "pt_interaction":
        add one to transit counter
    else (must be a "proper" activity, ie not pt_interaction):
        append counter - 2 to transits list
        reset counter
total number of transits = sum of transits list
```

2022-03-29 16:31 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
I am approving this as I do think your implementation is correct.

Although I am suspicious about:
```
for each trip:
    number of line switches = floor(number of pt interactions / 2) - 1
```

2022-03-29 16:43 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
subtracting 2 not working, become _every_ alighting was a PT interaction, not just the last one.

Here is an example from Londinium:
```
<activity type="gym" link="5221366961124175583_5221366963840338509" x="527449.0377700026" y="174907.7934215893" start_time="10:47:41" end_time="12:10:44" >
<leg mode="walk" dep_time="12:10:44" trav_time="00:02:41">
<activity type="pt interaction" link="5221366961597271735_5221366961597271735" x="527518.5209884992" y="174830.5783811345" start_time="12:13:25" end_time="12:13:26" >
<leg mode="bus" dep_time="12:13:26" trav_time="00:08:34">
<activity type="pt interaction" link="4237" x="527375.7371101471" y="175397.20261675102" start_time="12:22:00" end_time="12:22:01" >
<leg mode="walk" dep_time="12:22:01" trav_time="00:05:09">
<activity type="pt interaction" link="5221366977608376877_5221366977608376877" x="527201.7595597449" y="175500.23172701587" start_time="12:27:10" end_time="12:27:11" >
<leg mode="rail" dep_time="12:27:11" trav_time="00:11:52">
<activity type="pt interaction" link="5221377924493935121_5221377924493935121" x="525381.6323965725" y="178000.1913795474" start_time="12:39:03" end_time="12:39:04" >
<leg mode="walk" dep_time="12:39:04" trav_time="00:00:29">
<activity type="pt interaction" link="5221377923036634347_5221377923036634347" x="525380.6561217004" y="178023.08433860267" start_time="12:39:33" end_time="12:39:34" >
<leg mode="subway" dep_time="12:39:34" trav_time="00:04:28">
<activity type="pt interaction" link="5221377909342570047_5221377909342570047" x="525521.6932877643" y="178560.11270567012" start_time="12:44:02" end_time="12:44:03" >
<leg mode="walk" dep_time="12:44:03" trav_time="00:09:49">
<activity type="home" link="4624" x="525833.7741580525" y="178773.8747479139" start_time="12:53:52" >
``` 

This trip has 6/2-1=2 interchanges, not 6-4=2.

2022-03-29 17:21 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
checks out. I have been looking through some example outputs and these has been the case so far. I also understand why you are unsure - if there is a bus to bus interchange, using the same stop then perhaps there will not be a walk between.

I will see if i can check with columbus.

2022-03-29 17:23 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
exactly

2022-03-29 18:01 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
can you approve to merge then?

2022-03-29 18:03 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
best to add a test...

```
	<person id="Jim">
		<attributes>
			<attribute name="hid" class="java.lang.String">Jim</attribute>
			<attribute name="subpopulation" class="java.lang.String">electric</attribute>
		</attributes>
		<plan score="85.96536618601868" selected="no">
			<activity type="home" link="1-1" x="0.0" y="5100.0" end_time="07:25:00" >
			</activity>
			<leg mode="walk" dep_time="07:25:00" trav_time="00:02:36">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="07:27:36" trav_time="00:12:24">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="1-1" end_link="2-2" trav_time="00:12:24" distance="5001.0">{"transitRouteId":"city_bus","boardingTime":"07:30:00","transitLineId":"city_bus","accessFacilityId":"A","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="07:40:01" trav_time="00:10:59">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="3-3" trav_time="00:10:59" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"07:41:00","transitLineId":"city_bus2","accessFacilityId":"B","egressFacilityId":"F"}</route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" max_dur="00:00:00" >
			</activity>
			<leg mode="walk" dep_time="07:51:00" trav_time="00:00:00">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="3-3" end_link="2-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="work" link="2-3" x="10100.0" y="5100.0" end_time="16:30:00" >
			</activity>
			<leg mode="walk" dep_time="16:30:00" trav_time="00:00:00">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="2-3" end_link="3-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="16:30:00" trav_time="00:11:00">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="3-3" end_link="2-2" trav_time="00:11:00" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"16:31:00","transitLineId":"city_bus2","accessFacilityId":"F","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="16:41:01" trav_time="00:48:59">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="1-1" trav_time="00:48:59" distance="5010.0">{"transitRouteId":"city_bus","boardingTime":"17:20:00","transitLineId":"city_bus","accessFacilityId":"B","egressFacilityId":"A"}</route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="walk" dep_time="17:30:00" trav_time="00:02:36">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="home" link="1-1" x="0.0" y="5100.0" >
			</activity>
		</plan>

		<plan score="77.762093585343" selected="yes">
			<activity type="home" link="1-1" x="0.0" y="5100.0" end_time="07:39:44" >
			</activity>
			<leg mode="walk" dep_time="07:39:44" trav_time="00:02:36">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="07:42:20" trav_time="00:27:40">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="1-1" end_link="2-2" trav_time="00:27:40" distance="5001.0">{"transitRouteId":"city_bus","boardingTime":"08:00:00","transitLineId":"city_bus","accessFacilityId":"A","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="08:10:01" trav_time="00:40:59">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="3-3" trav_time="00:40:59" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"08:41:00","transitLineId":"city_bus2","accessFacilityId":"B","egressFacilityId":"F"}</route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" max_dur="00:00:00" >
			</activity>
			<leg mode="walk" dep_time="08:51:00" trav_time="00:00:00">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="3-3" end_link="2-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="work" link="2-3" x="10100.0" y="5100.0" end_time="16:18:37" >
			</activity>
			<leg mode="walk" dep_time="16:18:37" trav_time="00:00:00">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="2-3" end_link="3-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="16:18:37" trav_time="00:22:23">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="3-3" end_link="2-2" trav_time="00:22:23" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"16:31:00","transitLineId":"city_bus2","accessFacilityId":"F","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="bus" dep_time="16:41:01" trav_time="00:48:59">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="1-1" trav_time="00:48:59" distance="5010.0">{"transitRouteId":"city_bus","boardingTime":"17:20:00","transitLineId":"city_bus","accessFacilityId":"B","egressFacilityId":"A"}</route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" max_dur="00:00:00" >
			</activity>
			<leg mode="walk" dep_time="17:30:00" trav_time="00:02:36">
				<attributes>
					<attribute name="routingMode" class="java.lang.String">bus</attribute>
				</attributes>
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="home" link="1-1" x="0.0" y="5100.0" >
			</activity>
		</plan>

	</person>
```

2022-03-29 18:09 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
...let me know if you would like it reduced/simplified somehow

2022-03-30 10:07 UTC, fredshone commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
this is the output_experienced plan:
```
	<person id="Jim">
		<plan score="77.762093585343" selected="yes">
			<activity type="home" link="1-1" end_time="07:39:44" >
			</activity>
			<leg mode="walk" dep_time="07:39:44" trav_time="00:02:36">
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" start_time="07:42:20" end_time="07:42:20" >
			</activity>
			<leg mode="bus" dep_time="07:42:20" trav_time="00:26:06">
				<attributes>
					<attribute name="enterVehicleTime" class="java.lang.Double">28801.0</attribute>
				</attributes>
				<route type="default_pt" start_link="1-1" end_link="2-2" trav_time="00:26:06" distance="5001.0">{"transitRouteId":"city_bus","boardingTime":"08:00:01","transitLineId":"city_bus","accessFacilityId":"A","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" start_time="08:08:26" end_time="08:08:26" >
			</activity>
			<leg mode="bus" dep_time="08:08:26" trav_time="00:40:57">
				<attributes>
					<attribute name="enterVehicleTime" class="java.lang.Double">31164.0</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="3-3" trav_time="00:40:57" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"08:39:24","transitLineId":"city_bus2","accessFacilityId":"B","egressFacilityId":"F"}</route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" start_time="08:49:23" end_time="08:49:23" >
			</activity>
			<leg mode="walk" dep_time="08:49:23" trav_time="00:00:00">
				<route type="generic" start_link="3-3" end_link="2-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="work" link="2-3" x="10100.0" y="5100.0" start_time="08:49:23" end_time="16:18:37" >
			</activity>
			<leg mode="walk" dep_time="16:18:37" trav_time="00:00:00">
				<route type="generic" start_link="2-3" end_link="3-3" trav_time="00:00:00" distance="0.0"></route>
			</leg>
			<activity type="pt interaction" link="3-3" x="10100.0" y="5100.0" start_time="16:18:37" end_time="16:18:37" >
			</activity>
			<leg mode="bus" dep_time="16:18:37" trav_time="00:20:46">
				<attributes>
					<attribute name="enterVehicleTime" class="java.lang.Double">59401.0</attribute>
				</attributes>
				<route type="default_pt" start_link="3-3" end_link="2-2" trav_time="00:20:46" distance="5001.0">{"transitRouteId":"city_bus2","boardingTime":"16:30:01","transitLineId":"city_bus2","accessFacilityId":"F","egressFacilityId":"B"}</route>
			</leg>
			<activity type="pt interaction" link="2-2" x="5000.0" y="5000.0" start_time="16:39:23" end_time="16:39:23" >
			</activity>
			<leg mode="bus" dep_time="16:39:23" trav_time="00:44:10">
				<attributes>
					<attribute name="enterVehicleTime" class="java.lang.Double">60001.0</attribute>
				</attributes>
				<route type="default_pt" start_link="2-2" end_link="1-1" trav_time="00:44:10" distance="25014.0">{"transitRouteId":"city_bus","boardingTime":"16:40:01","transitLineId":"city_bus","accessFacilityId":"B","egressFacilityId":"A"}</route>
			</leg>
			<activity type="pt interaction" link="1-1" x="0.0" y="5000.0" start_time="17:23:33" end_time="17:23:33" >
			</activity>
			<leg mode="walk" dep_time="17:23:33" trav_time="00:02:36">
				<route type="generic" start_link="1-1" end_link="1-1" trav_time="00:02:36" distance="130.0"></route>
			</leg>
			<activity type="home" link="1-1" x="0.0" y="5100.0" start_time="17:26:09" >
			</activity>
		</plan>

	</person>
```

2022-04-01 09:26 UTC, Theodore-Chatziioannou commented on pam/scoring.py
> +                        in_transit -= 1 # the first PT vehicle does not incur a line switch penalty
@fredshone I have now added the above test.

2022-04-04 09:20 UTC, fredshone commented on tests/test_12_scoring.py
> +    pass
pretty sketchy test

2022-04-04 09:22 UTC, Theodore-Chatziioannou commented on tests/test_12_scoring.py
> +    pass
removed

2022-04-04 09:44 UTC, fredshone approved these changes

2022-04-04 09:58 UTC, merged