Population combiner
arup-group/pam pull request #157
Opened 2022-07-14 12:59 UTC by alex-kaye

This combines multiple populations via the pam cli. 

I would like to add a validation check that avoids existing `combined_population.xml` files being overwritten, if this file already exists. My attempt at adding this is `cli.py line 180`. 

Please could you review and add any improvements.

2022-07-14 14:31 UTC, fredshone requested changes
looks good, nice clean pattern, some minor comments and then we need to add a few tests. Let me know once you're done and I'll add some for you. Then we will go through together.

2022-07-14 14:31 UTC, fredshone commented on pam/cli.py
> +        population_output.abort()
(not tested)

2022-07-14 14:31 UTC, fredshone commented on pam/cli.py
> +        population_output.abort()
ok now i read the docs... doesn't look like what you want is going to obviously work as a call-back. Seems it is hard-coded to always ask y/n regardless of exists or not.

I think you will need to add you own logic at the start of the command (after receiving the args). Something like:

```
def callback_if_exists(path):
    if os.path.exists(path) == True:
       if input(f"{population_output} exists, overwrite? [y/n]:") .lower() in ["y", "yes", "ok"]:
           return None
       else:
           raise UserWarning(f"Aborting to avoid overwrite of {population_output}")
```

2022-07-14 14:31 UTC, fredshone commented on pam/cli.py
> +    "--population_output", "-o", type=click.Path(exists=False, writable=True), default=os.getcwd()+"\combined_population.xml",
I think just `default="combined_population.xml"` will work fine?

2022-07-14 14:31 UTC, fredshone commented on pam/cli.py
> +
4 blank lines? :)

2022-07-14 14:31 UTC, fredshone commented on pam/operations/population_combiner.py
> +            version=12
your command accepts a version arg. Users will prob assume it works on both the read and write...

personally don't mind if you hard code it all to 12. But otherwise make accessible here as well.

2022-07-14 15:36 UTC, alex-kaye commented on pam/cli.py
> +        population_output.abort()
nice! thank you. That works.

I didn't define a `callback_if_exists` function but just used the logic. It seems each cli command only likes to be passed one function.

2022-07-14 15:37 UTC, alex-kaye commented on pam/cli.py
> +    "--population_output", "-o", type=click.Path(exists=False, writable=True), default=os.getcwd()+"\combined_population.xml",
I keep getting permission errors without defining the cwd, so have kept this in

2022-07-27 16:00 UTC, fredshone approved these changes
let's get this merged

2022-07-27 16:10 UTC, merged

2022-07-27 16:20 UTC, alex-kaye commented
thank you - were the tests okay/sufficient?