ensures matsim read write maintains data
arup-group/pam pull request #167
Opened 2022-09-12 16:47 UTC by fredshone

Changes intended to ensure no data is lost from MATSim plans when read/writing. This mainly includes the unchosen plans, but also other attributes such as link ids and pt interactions with durations (as recently spotted and fixed for elara).

Loosing the unselected plans from bitsim was increasing runs times by 30% (after a pam read/write).

The cli exposes a flag called `--keep_non_selected/selected_only` which defaults to `keep`. I've made this optional because there will be pretty chonky memory implications.

There's bits and other bobs (this was a long lived branch) - but nothing major and no breaks.

2022-09-29 08:48 UTC, fredshone commented
bump

2022-09-30 17:07 UTC, Theodore-Chatziioannou requested changes
thanks Fred, this looks great. Would you mind doing two changes as per my comments:
- make sure the "keep_non_selected_plans" is passed correctly/consistently between methods
- add a test (fixture) reading/writing non-selected plans

2022-10-03 12:24 UTC, fredshone commented on pam/utils.py
i like to keep a line between the package imports and the local imports

2022-10-03 12:29 UTC, fredshone commented on pam/cli.py
> +            keep_non_selected=keep_non_selected,
definitely thank you 🙇🏻

2022-10-03 15:12 UTC, fredshone commented
@Theodore-Chatziioannou thank you for your review - it led me to a few other snafus... All fixed now

2022-10-03 15:26 UTC, merged