Vehicles api
arup-group/pam pull request #215
Opened 2023-07-10 18:18 UTC by fredshone

WIP adds "MATSim vehicles" functionality.

Still has rough edges, documentation, changelog (ahem) and better coverage, but sharing for any high level complaints on the implementation which is awkward.

# Aims:

At a super high level I am trying to facilitate two main use cases:

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 
You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Memory profiling tests pass (see [here](https://arup-group.github.io/pam/contributing/coding/#memory-profiling) for more details)
- [ ] Tests added to cover contribution
- [ ] Documentation updated

2023-07-12 09:15 UTC, brynpickering commented on pam/core.py
> +        Update veh population from agents.
not sure if you are mitigating the risk of misspelling "vehicle(s)" by using "veh(s)", but it does seem more readable to use the long format throughout.

2023-07-12 09:17 UTC, brynpickering commented on pam/core.py
> +    def safe_add_veh_to_agent(self, hid: str, pid: str, mode: str, v: Vehicle) -> bool:
Any reason to prepend with "safe"? If you have an unsafe alternative method (I don't see one), it would be better to have `safe` as a boolean input arg and merege the two methods together.

2023-07-12 09:22 UTC, brynpickering commented on pam/core.py
>              chargers |= set(v.charger_types.split(","))
```suggestion
            chargers.update(v.charger_types.split(","))
```

2023-07-12 09:23 UTC, brynpickering commented on pam/core.py
> +        vehicles: dict[str:Vehicle] = {},
```suggestion
        vehicles: dict[str, Vehicle] = {},
```

2023-07-12 09:24 UTC, brynpickering commented on pam/core.py
>          if home_location is not None:
I would probably do this with the args that default to empty dicts too. Generally a bad idea to have mutable objects as default values.

2023-07-12 09:27 UTC, brynpickering commented on pam/read/matsim.py
> +    vehicles_manager: Optional[VehicleManager] = VehicleManager(),
Only use `Optional` if `None` is a viable input.

2023-07-12 09:58 UTC, brynpickering commented on tests/conftest.py
> +FIXTURES_DIR = Path(__file__).parent.parent / "pam" / "fixtures"
```suggestion
import importlib_resources
FIXTURES_DIR = importlib_resources.files("pam") / "fixtures"
```

2023-07-25 15:50 UTC, fredshone commented on pam/core.py
>          if home_location is not None:
I don't follow - `vehicles` is passed as an arg and defaults to {}?

2023-07-25 16:44 UTC, brynpickering commented on pam/core.py
>          if home_location is not None:
Yes, nothing should default to `{}` in the function signature. Example of why:

``` python
def foo(bar, x = {}):
    x[bar] = 1
    return x

In [2]: foo(2)
Out[2]: {2: 1}

In [3]: foo(3)
Out[3]: {2: 1, 3: 1}  # expectation is {3: 1}
```

Better to do `x = None` and then handle the undefined case in the function.

2023-07-26 17:29 UTC, fredshone commented
ready for review again

2023-07-27 15:13 UTC, brynpickering commented on pam/vehicles.py
> +@dataclass(frozen=True)
Is this the only dataclass that needs `frozen` set? I see you added it for py3.11 compatibility - why do the others not need it?

2023-07-28 10:34 UTC, brynpickering requested changes

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +            self.vehicles = vehicles
I would just make vehicles a property of the person which returns the vehicles dictionary. Ideally you would set `self._vehicles` in `__init__` and then return `self._vehicles` in the `vehicles` property. This way, you can't accidentally override `self.vehicles` elsewhere

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +    def vehicles(self):
replace with property that returns `self._vehicles`

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +    def evs(self):
replace with property that does the same thing, but returns a dictionary or an iterator of one

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +    def evs(self):
I would prefer a direct dicitonary so that it acts in the same way as `Person.vehicles`

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +        for k, v in self.vehicles_manager.types():
There seems no getting around using `yield` for spitting out tuples from nested dicts (as is done elsewhere in PAM, inc. in core), but for flat dictionaries, `iter(dict_name.items())` would be better.

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +    def add_veh_to_agent(self, hid: str, pid: str, mode: str, vehicle: Vehicle):
Is there a danger to having the vehicles manager only available in the `Population` class? A user could add a vehicle to a `Person` directly that has an unknown type. In fact, that is what you're doing in the example notebook, rather than using this method.

I'd either have this as your only method to add a vehicle to an agent (hiding the `Person.vehicles` dictionary from public view), or propagate the vehicles manager to Households and Persons when they are added to the population, so that when you add a vehicle to a Person, it checks its validity within the vehicle manager.

2023-07-28 10:34 UTC, brynpickering commented on pam/core.py
> +    def add_veh_to_agent(self, hid: str, pid: str, mode: str, vehicle: Vehicle):
Example drawing on your notebook:

This passes, but is inconsistent:
``` python
pop.vehicles_manager.add_type("small_car", vehicles.VehicleType())
pop.vehicles_manager.add_type("large_car", vehicles.VehicleType(length=15, width=2))
for hid, pid, p in pop.people():
    p.vehicles = {
            "car": vehicles.ElectricVehicle(pid, type_id="medium_car", battery_capacity=100)
        }
```

This fails as expected:
``` python
pop.vehicles_manager.add_type("small_car", vehicles.VehicleType())
pop.vehicles_manager.add_type("large_car", vehicles.VehicleType(length=15, width=2))
for hid, pid, p in pop.people():
    pop.add_veh_to_agent(hid, pid, "car", vehicles.ElectricVehicle(pid, type_id="medium_car", battery_capacity=100))
```

2023-07-28 10:34 UTC, brynpickering commented on examples/data/example_data/evs.xml
Add these to a subdirectory specific to the vehicles example, otherwise it's unclear when looking in the data directory that they are connected to each other and not to anything else in the `example_data` subdir

2023-07-28 10:34 UTC, brynpickering commented on pam/write/matsim.py
> +    attributes_path: Union[Path, str, None] = None,
```suggestion
    attributes_path: Optional[Union[Path, str]] = None,
```
Although the result is the same, this is clearer as a hint, saying that useful inputs are `Path`/`str` and `None` is a placeholder to indicate you want to ignore that arg.

2023-07-28 10:34 UTC, brynpickering commented on pam/write/matsim.py
> +    attributes_path: Union[Path, str, None] = None,
Same with the below args

2023-07-28 10:34 UTC, brynpickering commented on pam/write/matsim.py
> +    version: int = None,
It should be wrapped in `Optional` since it defaults to None...
Since it is legacy, can you add a deprecation warning that is thrown when `version` is not None, telling the user that `version` will have no effect and the arg will be removed entirely in e.g. version `0.3.0`

2023-07-28 10:34 UTC, brynpickering commented on pam/write/matsim.py
> +            {"class": "org.matsim.vehicles.PersonVehicles", "name": str("vehicles")},
why `str("vehicles")` and not `"vehicles"`

2023-08-03 09:49 UTC, fredshone commented on pam/vehicles.py
> +@dataclass(frozen=True)
I think this occurs because the dataclass is used as a default in the `VehicleType` class:

```
@dataclass
class VehicleType:
    capacity: CapacityType = CapacityType()
```

this risks the classic (you reminded me last week) mutable default bug where the default value gets changed by each instatiation. I think the dataclasses mod is picking this up.

Rather than freeze I can also do this to keep it mutable:

```
@dataclass
class VehicleType:
    capacity: CapacityType = field(default_factory=lambda: CapacityType())
```

From [docs](https://docs.python.org/3/library/dataclasses.html#dataclasses.field):

> default_factory: If provided, it must be a zero-argument callable that will be called when a default value is needed for this field. Among other purposes, this can be used to specify fields with mutable default values, as discussed below. It is an error to specify both default and default_factory.

For some reason I cannot call `CapacityType()` directly  (I though this would be a "callable") - so i add the lambda.

2023-08-03 10:25 UTC, fredshone commented on pam/core.py
> +            self.vehicles = vehicles
removed the iterator (i agree with your suggestion) but pam elsewhere just exposes mutable data and i don't want to get into get/set methods everywhere

2023-08-03 10:58 UTC, brynpickering commented on pam/vehicles.py
> +@dataclass(frozen=True)
Would it work as just `CapacityType` (no brackets)?

2023-08-03 16:53 UTC, fredshone commented on pam/core.py
> +        for k, v in self.vehicles_manager.types():
Thanks for this - I cleaned out the unnecessary ones and replaced with @property where possible. Otherwise I am going to expect people to interact with the attributes directly. This is generally the case throughout.

2023-08-03 16:55 UTC, fredshone commented on pam/write/matsim.py
> +            {"class": "org.matsim.vehicles.PersonVehicles", "name": str("vehicles")},
probably a mental breakdown

2023-08-03 17:09 UTC, fredshone commented on pam/core.py
> +    def add_veh_to_agent(self, hid: str, pid: str, mode: str, vehicle: Vehicle):
yeah this is the crux of the PR and i agree with comment. But... I am still keen to maintain a simple python object based representation that allows for basic use cases (no matsim) that don't care about vehicle types in an especially systematic way.

So for now I've added a new `Population.check_vehicles()` method and included in the example. I will refine docs and await a third part to decide :)

2023-08-09 06:43 UTC, brynpickering commented
You seem to have deleted the data that the example notebook needs to run, hence the failing tests.

2023-08-09 06:47 UTC, brynpickering commented on pam/core.py
> +    def add_veh_to_agent(self, hid: str, pid: str, mode: str, vehicle: Vehicle):
OK, that makes sense. Minor point if keeping `add_veh_to_agent`: `agent` isn't really used in PAM, so should it be `add_vehicle_to_person`?

2023-08-09 10:33 UTC, fredshone commented
huzzah

2023-08-14 16:29 UTC, KasiaKoz commented on pam/vehicles.py
> +            k (str): Vehicle type key.
I feel like we should add a `type_id` to `VehicleType` class to use instead of `k` here, otherwise the link to the type name is only in the manager.. unless you want to be able to use the same `VehicleType` with different type keys/names?...

2023-08-16 11:02 UTC, fredshone commented on pam/vehicles.py
> +            k (str): Vehicle type key.
I have some struggles and doubts with this throughout:

(i) It is convenient to keep the id as a hash key, so that I can access cheaply.
But also (ii) the Vehicles class needs an "internal" veh_id so that it can be held as an agent attribute (eg `{"car": Vehicle(...)}`.
But then (iii) I don't like the duplication of the id, eg `{"type_0": VehicleType("type_0")}`.

So to summarise, I actually prefer this key value representation: `{"type0": VehicleType()}`. But I have to break it for vehicles because of the broader requirements of what i implemented.

Option 1: keep as is, eg `{"type0": VehicleType(), type1": VehicleType(), ...}`.
Option 2: move to list, eg `[VehicleType("type0"), VehicleType("type1"), ...]`, this removes key but slows lookups.
Option 3: duplicate, eg `{"type0": VehicleType("type0"), type1": VehicleType("type1"), ...}`.

3 is not much work but adds duplication and the possibility of inconsistency. ie what if someone does this: `VehicleManager.veh_types["typO"] = VehicleType("typE")`.

Same snaffu exists for Vehicles, but is less likely because the link is generally established in the population where the key is the mode. Whereas types only exist in the manager.

The other reason I had for using keys is that the Vehicles can then reference the key of the VehcileType, rather than the VehicleType itself. This seemed safer to me, because it would make it harder for someone changing the values of a type (such as the capacity) for one person's vehicle, accidentally changing it for everyone else.

Gnerally I realise this happens because we are storing VehcileType data for each Vehcile as a reference rather than data belonging to the Vehcile itself. But I am happy to do this as it reduces wasted memory and is consistent with MATSim.

Not sure if any of these helps. Let me know what you think now?

2023-08-16 13:50 UTC, brynpickering commented on pam/vehicles.py
> +            k (str): Vehicle type key.
There's a lot of confusion introduced by the various ways you can assign things in this PR. I know it is there to provide flexibility, but might still benefit from tightening the ways in which assignment is possible. I wouldn't allow access to `VehicleManager.veh_types`. This would be a private property of the manager that can only be added to by calling `add_type`. This way, the internal data structure (dicts with `ID: VehicleType`) can exist with duplication of type ID, but the user doesn't see it. They can then add a type by calling `add_type(VehicleType(type_name))`. Would that work or am I being naive about where the type is assigned and accessed in the code?

2023-08-16 15:48 UTC, fredshone commented on pam/vehicles.py
> +            k (str): Vehicle type key.
ok - I have gone for option 3: `{"type0": VehicleType("type0"), type1": VehicleType("type1"), ...}`

and as Bryn suggests, I've made the data more "private", such that there is no direct interaction with the vehicles manager encouraged. See example notebook for "proof".

2023-08-16 15:56 UTC, KasiaKoz commented on pam/vehicles.py
> +            k (str): Vehicle type key.
I like that option and hiding the vehicle manager. 
Sorry for not replying earlier, just wanted to add, in my implementation I chose to make the objects immutable with `@dataclass(frozen=True)` which makes it a bit safer (also from real life perspective vehicle specs don't really change, you might get a new vehicle with different spec) but maybe overkill and I think you had reasons for changing that which I can't recall right now

2023-08-16 15:58 UTC, fredshone commented on pam/vehicles.py
> +            k (str): Vehicle type key.
I resolve this

2023-08-17 09:53 UTC, KasiaKoz approved these changes

2023-08-17 16:42 UTC, fredshone commented
@brynpickering I think i need you nod - pretty sure I've incorporated all your feedback...

2023-08-18 05:52 UTC, brynpickering approved these changes

2023-08-18 08:52 UTC, merged