fix for #221
arup-group/pam pull request #222
Opened 2023-07-18 09:25 UTC by fredshone

Fixes #221.

Provides "pt" simplification based on removing "pt interaction" activities. Added coverage but am also going to test simplified plans in matsim. Will update.

## Checklist

- [ ] CHANGELOG updated
- [ ] Memory profiling tests pass (see [here](https://arup-group.github.io/pam/contributing/coding/#memory-profiling) for more details)
- [ ] Tests added to cover contribution
- [ ] Documentation updated

2023-07-19 13:24 UTC, brynpickering requested changes
A few minor comments.

On the implementation, `tripify` seems very specific to public transport interaction legs/activities since you carefully remove the leg leading up to a `pt interaction` that comes before a public transport leg, then remove the leg following a `pt interaction` that comes after a public transport leg (I could only really infer this from the tests), e.g.:

``` python 
[                
    Activity(act="home", loc=Point(0, 0)),
    Leg(mode="walk", distance=100, start_loc=Point(0, 0), end_loc=Point(100, 0)),
    Activity(act="pt interaction", loc=Point(100, 0)),
    Leg(mode="bus", distance=1000, start_loc=Point(100, 0), end_loc=Point(100, 1000)),
    Activity(act="pt interaction", loc=Point(100, 1000)),
    Leg(mode="walk", distance=20, start_loc=Point(100, 1000), end_loc=Point(0, 1000)),
    Activity(act="work", loc=Point(0, 1000)),
]
```

becomes

``` python
[
    Activity(act="home", loc=Point(0, 0)),
    Leg(mode="bus", distance=1120, start_loc=Point(0, 0), end_loc=Point(0, 1000)),
    Activity(act="work", loc=Point(0, 1000)),
]
```

However, the docstring doesn't explain that this is the expected result, instead of, say:

``` python
[                
    Activity(act="home", loc=Point(0, 0)),
    Leg(mode="walk", distance=1120, start_loc=Point(0, 0), end_loc=Point(0, 1000)),
    Activity(act="work", loc=Point(0, 1000)),
]
```
If it's specific to removing public transport interactions, then I would make that much more obvious.

2023-07-19 13:24 UTC, brynpickering commented on pam/activity.py
> +        pt interaction events result from complex matsim plans.
Add Args section as with `tripify`

2023-07-19 13:24 UTC, brynpickering commented on pam/activity.py
>      def trips(self, ignore: list[str] = ["pt interaction", "pt_interaction"]) -> str:
`ignore` -> `skip` (or vice versa) to align argument names between methods?

2023-07-19 13:24 UTC, brynpickering commented on pam/read/matsim.py
> +        data = attr.get("class")
In the if statements, assign the value to a variable, e.g. `typed_attr`, then assign that to `attributes[attr.get("name")]` at the end. This reduces lines that need to change in future if `attributes[attr.get("name")]` changes for any reason.

2023-07-19 13:24 UTC, brynpickering commented on pam/read/matsim.py
> +            attributes[attr.get("name")] = attr.text == "true"
can it strictly only ever be "true"? not "TRUE" or "True"? If you're unsure, then do `attr.text.lower()`

2023-07-19 13:24 UTC, brynpickering commented on tests/test_02_activity_trips.py
> +@pytest.mark.parametrize(
Split in two: ones where you don't expect a change in the data and ones where you do. Then you can reduce reproduction of code in the test where you don't expect a change (because `day == expected`)

2023-07-24 17:29 UTC, fredshone commented
Good feedback thanks @brynpickering - I have addressed all as you suggest.

2023-07-25 08:08 UTC, merged