Freight route optimisation
arup-group/pam pull request #231
Opened 2023-07-28 09:14 UTC by val-ismaili

Based on the route optimisation challenge [here](https://github.com/arup-group/activity-synthesis/blob/main/location_choice/example_freight_location.ipynb) showing the approximated `greedy_tsp` as the most effective balance between optimised routing and computing time, this has been implemented within `tour.py` for stop sequencing of freight delivery locations.

During implementation, it was found that the existing code allowed for duplicate sampling of delivery locations within the same sequence as well as the possibility for the depot being sampled as a delivery location (if the facility has both tags). Both these issues have been fixed within `sample_destinations()` in `tour.py`. Associated test has been added with `test_unique_stops()` in `test_09_samplers_tour.py`. This was discovered when testing on toy data which resulted in occasional duplicate sampling of delivery locations resulting in a distance_matrix with zero distances resulting in an incomplete graph - test is added for this too under `test_distance_matrix_is_complete`.

## Checklist
- [ ] CHANGELOG updated
- [ ] Memory profiling tests pass (see [here](https://arup-group.github.io/pam/contributing/coding/#memory-profiling) for more details)
- [ ] Tests added to cover contribution
- [ ] Documentation updated

2023-07-28 11:31 UTC, brynpickering requested changes
Some minor comments. For docstrings, the easiest approach is to set the type hints in your function signature and then use [autodocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) in vscode to pre-generate the docstring template. Then you just need to add context.

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +            d_zone = FrequencySampler(self.d_dist.index, self.d_dist[self.d_freq]).sample()
self.d_dist can supposedly be an `Iterable` (see class init type hints), in which case it wouldn't have an `index`, on a pandas dataframe would. Do you only ever expect `d_dist` to be a dataframe now?

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        """Samples a delivery zone (d_zone) as a string, dependent on the presence of a threshold matrix
delivery -> destination? In the class docstring it is `destination` while here it is `delivery`, which is a bit confusing as to whether `d` now means something different

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
>          for j in range(self.stops):
while we're here (I know you haven't edited this line in this commit), `j` -> `stop`. It's always good to be descriptive.

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +    def sample_destinations(self, o_loc):
type hint and docstring needed

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +    def create_distance_matrix(self, o_loc, d_seq):
type hints and docstrings needed

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        # extact o_loc coordinates into array
spelling, `extract`

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        locs = np.concatenate([o_location, d_locations], 0)
Could simplify as:

```
locations = [[o_loc.x, o_loc.y]]
for facility in [d["destination_facility"] for d in d_seq]]:
    locations = np.append(locations, [[facility.x, facility.y]], 0)
```

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        d_seq = [d_seq[order] for order in seq]
```suggestion
        d_seq = [d_seq[order - 1] for order in seq[1:-1]]
```

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        d_seq = [d_seq[order] for order in seq]
It's shorter and I think it's a bit easier to understand what's going on

2023-07-28 11:31 UTC, brynpickering commented on pam/samplers/tour.py
> +        d_seq = TourPlanner.reorder_deliveries(self, d_seq, seq)
Call this something else so that if you come to debug at some point you have access to the original `d_seq` to compare the difference

2023-07-28 11:31 UTC, brynpickering commented on tests/test_09_samplers_tour.py
> +    assert o_loc not in deliveries, "o_loc has been sampled as a delivery location"
separate into its own test

2023-07-31 14:24 UTC, fredshone requested changes
NIce job with this PR.

Definately tackle Bryns comments. Getting the type hints is especially important for this module - there is loads of passing complex data types (dataframes and geodataframes) and making assumptions about column names and indexes. Tackling all these is beyond the scope of this PR but I wanted to grumble about it.

While you are here please also:

(i) Please rename ActivityDuration to something without the word "Activity" in. I found this comfusing as it is also used for trip durations.

(ii) please rename TourPlanner to something that describes the methodology (TSPPlanner maybe).

2023-07-31 14:24 UTC, fredshone commented on tests/test_09_samplers_tour.py
> +
fixtures make a bunch of features available (like scoping). Most of which we don't use - but I think it is still a good idea to use the fixture decorator simply to communicate to the reader that something is a fixture - so nice job.

I do find it weird that this fixture has a random sampler in it (TourPlanner) so can return different things each time it is run (?). Much prefer this return a hardcoded o_loc and d_seq.

As an aside - there is a place for randomness in testing, but not often and normally i would expect it to look like:

```
def test_sampler_bias(sampler):
   samples = [sampler.sample() for _ in range(1000)]
   assert samples.mean() < 0.5  # some statistical test
```

2023-07-31 14:24 UTC, fredshone commented on pam/samplers/tour.py
> +        """Samples a delivery zone (d_zone) as a string, dependent on the presence of a threshold matrix
avoid freight specific language

2023-08-03 08:56 UTC, Theodore-Chatziioannou requested changes
That's great @val-ismaili ! I also checked the application of the method and seems to work as intended. Some minor comments only. I understand @divyasharma-arup encountered a small error when sampling with a threshold value - worth checking with her if we need to address or handle it.

2023-08-03 11:59 UTC, divyasharma-arup commented on pam/samplers/tour.py
> +            d_zone = FrequencySampler(self.d_dist.index, self.d_dist[self.d_freq]).sample()
yes, I believe `d_dist` will consistently be a dataframe, and the type hint should reflect this. I thnk the confusion came from the `FrequencySampler` class, where dist can be either an Iterable or dataframe. When specifically sampling the destination distribution (`d_dist`), however, the intention is for this to be a dataframe. @val-ismaili, would you be able to update the type hint in `TourPlanner` to only be `pd.DataFrame`?

2023-08-03 12:11 UTC, divyasharma-arup commented
> That's great @val-ismaili ! I also checked the application of the method and seems to work as intended. Some minor comments only. I understand @divyasharma-arup encountered a small error when sampling with a threshold value - worth checking with her if we need to address or handle it.

Thanks Theo, I'll modify the issue with the threshold value in a separate PR -- I also need to make some changes to the ValidateTourOD class. I'm partially considering removing the threshold functionality altogether, and leaving it to the user to reduce their matrix size vs. the code doing it for them. That would require changing existing notebooks & scripts though.

2023-08-03 12:51 UTC, val-ismaili commented on pam/samplers/tour.py
> +            d_zone = FrequencySampler(self.d_dist.index, self.d_dist[self.d_freq]).sample()
typehint changed to `pd.DataFrame` only

2023-08-03 12:52 UTC, val-ismaili commented on pam/samplers/tour.py
> +        """Samples a delivery zone (d_zone) as a string, dependent on the presence of a threshold matrix
language changed to refer to destinations and stops rather than deliveries.

2023-08-03 12:52 UTC, val-ismaili commented on pam/samplers/tour.py
>          for j in range(self.stops):
`j` -> `stop`

2023-08-03 12:53 UTC, val-ismaili commented on pam/samplers/tour.py
> +    def sample_destinations(self, o_loc):
added

2023-08-03 12:53 UTC, val-ismaili commented on pam/samplers/tour.py
> +    def create_distance_matrix(self, o_loc, d_seq):
added

2023-08-03 12:57 UTC, val-ismaili commented on pam/samplers/tour.py
> +        locs = np.concatenate([o_location, d_locations], 0)
agreed that can be simplified. but used an [alternative](https://github.com/arup-group/pam/pull/231/commits/51d302726821fea08161933efbd60689dd56f638#diff-47ea7e3fa3e34efd29dfa0a0980e34f9e7602e8c29f472fc4389126b8397fee9R380) way which (i think) is more efficient

2023-08-03 12:58 UTC, val-ismaili commented on pam/samplers/tour.py
> +        d_seq = [d_seq[order] for order in seq]
agreed.

2023-08-03 12:58 UTC, val-ismaili commented on pam/samplers/tour.py
> +        d_seq = TourPlanner.reorder_deliveries(self, d_seq, seq)
changed to `d_optimised_seq`

2023-08-03 13:01 UTC, val-ismaili commented on tests/test_09_samplers_tour.py
> +    assert o_loc not in deliveries, "o_loc has been sampled as a delivery location"
seperated into additional [test](https://github.com/arup-group/pam/pull/231/commits/51d302726821fea08161933efbd60689dd56f638#diff-c548d559d784b9b8489f5833d2d6fddc2bf2b7a5244f5be4e6f9ca9b9cd69ee9R347)

2023-08-03 14:02 UTC, brynpickering commented on pam/samplers/tour.py
> +        locs = np.concatenate([o_location, d_locations], 0)
Yep, more time efficient. Nice. Can you change one of the `d`s in your list comprehension to avoid confusion?

2023-08-03 14:26 UTC, val-ismaili commented on tests/test_09_samplers_tour.py
> +
@fredshone noted about the general point about randomness in testing. 

I purposely did it this way though because `TourPlanner.sample_destinations()` is what prevents duplicate sampling of destinations within a tour, and  the origin being sampled as a destination. By doing it this way, if someone makes a change down the line that removes this, the tests i added `test_unique_stops` and `test_origin_not_in_stops` can fail. If we hardcode `o_loc` and `d_seq` we won't be testing this and then if the `greedy_tsp()` returns an error of incomplete graph it's harder to understand where the cause is.

2023-08-03 14:36 UTC, val-ismaili commented
To summarise changes I've made following all the comments:
- Added / improved typehints & docstrings.
- General readability and simplification updates.
- I've kept the randomness in the test fixture as per this [response](https://github.com/arup-group/pam/pull/231#discussion_r1283287006).
- `ActivityDuration` class -> `DurationEstimator` (only references within `TourPlanner` class currently so easy change).
- `TourPlanner` remains the same name with added detail in the docstring describing use of TSP. Rationale is that this class may continue to develop and incorporate choices between different sequencing algorithms so keeping it generic makes sense. Also would break old scripts.

2023-08-03 18:07 UTC, Theodore-Chatziioannou approved these changes

2023-08-03 18:08 UTC, merged