Doc update
arup-group/pam pull request #239
Opened 2023-08-18 17:06 UTC by fredshone

Update to docs:
- minor changes to readme intro
- new and fixed examples, including some simple renaming

Generally aiming to ease entry barrier to new users.

Also ended up making a fix to the "grid optimiser" which I wound to be broken (woops).

I also relaxed nbqa ruff to allow out of order imports in notebooks. For the basic notebooks i prefer to add the imports as they are used to keep code minimal.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator. 
All others should be checked by the reviewer(s). 
You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Memory profiling tests pass (see [here](https://arup-group.github.io/pam/contributing/coding/#memory-profiling) for more details)
- [ ] Tests added to cover contribution
- [ ] Documentation updated

2023-08-22 14:39 UTC, brynpickering requested changes
Nice to see these updates! I'll push a fix to the mkdocs navigation to get the new notebooks names transferred into the online docs. I'll also probably add a hook to just fetch all the files in `examples` and add them to the nav tree automatically, rather than expecting maintainers to remember to update that.

Can you add the PAM logo to the top of the `index.md` file in the docs and if you have a square version of it (just the `P`?), we can use that as the docs favicon.

2023-08-22 14:39 UTC, brynpickering commented on examples/01_basics.ipynb
> +    "This notebook demonstrates the core mechanics of the PAM by creating a demonstration population."
```suggestion
    "This notebook demonstrates the core mechanics of PAM by creating a demonstration population."
```

2023-08-22 14:39 UTC, brynpickering commented on examples/02a_tabular_read_write.ipynb
> +    "1. Read\n",
It's quite easy to add hyperlinks here, i.e. `1. [Read](#read-tabular-format)`. Whenever you have a brief TOC at the start of the notebook, I'd add those.

2023-08-22 14:39 UTC, brynpickering commented on examples/02a_tabular_read_write.ipynb
> +    "### Step 1\n",
Drop it down to the 4th level so it doesn't turn up in the documentation TOC (looks weird by itself): 

<img width="220" alt="image" src="https://github.com/arup-group/pam/assets/17178478/f732dad9-beb1-43ed-a4ff-2d0084386189">

2023-08-22 14:39 UTC, brynpickering commented on examples/03_read_modify_write.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABOsAAAHbCAYAAACa3h5OAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8pXeV/AAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOz
Drop down one level (`##`)

2023-08-22 14:39 UTC, brynpickering commented on examples/16_advanced_matsim_warmstarting.ipynb
> +    "For example, consider the case where we have the outputs from a MATSim baseline simulation. We want to test a new scenario that makes a minor change to some parts of the network, this includes r
```suggestion
    "For example, consider the case where we have the outputs from a MATSim baseline simulation. We want to test a new scenario that makes a minor change to some parts of the network, this includes removing some links. We would like to reuse the output baseline plans. They contain our best initial guess for agent choices for times, modes and routes, including for unselected plans. However, we cannot resue these plans as they are, because they include routes that are now impossible due to our new scenario removing some links.\n",
```

2023-08-22 14:39 UTC, brynpickering commented on examples/16_advanced_matsim_warmstarting.ipynb
> +    "- crop (but note this does not currently support unselected plans)\n",
It should be possible to cross reference to these in the CLI API reference page. I wonder if [crop][#pam-crop] would work? Need to experiment.

2023-08-22 14:39 UTC, brynpickering commented on pam/optimise/grid.py
> +    """Checks all permutations of a plan's activity start times and durations, finds plan
First sentence a docstring should be short, followed by a blank line, then all the additional info. Makes it easier to read the docstring info as a tooltip.

2023-08-22 14:39 UTC, brynpickering commented on pam/optimise/grid.py
> +    plan: Plan, plans_scorer: PlanScorer, config: dict = {}, step: int = 900, copy=True
defaulting to `{}`!

2023-08-22 14:39 UTC, brynpickering commented on pam/optimise/grid.py
> +def latest_start_time(plan: Plan, leg_index: int):
docstring

2023-08-22 14:39 UTC, brynpickering commented on pam/optimise/random.py
> +    This is not seriously suggested as a sensible approach, it is supplied for example only.
😄

2023-08-22 14:39 UTC, brynpickering commented on pam/optimise/random.py
> +    """Rearrange input plan into random new plan, maintaining activity sequence and trip durations."""
Args

2023-08-22 14:39 UTC, brynpickering commented on tests/test_27_optimise_random.py
> +        assert stopper.stop(1) is False
More Pythonic: `assert not stopper.stop(1)`. But also maybe less readable 🤷‍♂️

2023-08-23 07:15 UTC, brynpickering commented on examples/16_advanced_matsim_warmstarting.ipynb
> +    "- crop (but note this does not currently support unselected plans)\n",
```suggestion
    "- [crop](../../api/cli/#pam-crop) (but note this does not currently support unselected plans)\n",
```

2023-09-08 13:59 UTC, fredshone commented on tests/test_26_optimise_grid.py
> +    assert grid.traverse(dummy_scorer, {}, plan, 1, 0, 3, recorder) is None
yeah ok i remove the assertion

2023-09-08 14:03 UTC, fredshone commented on tests/test_26_optimise_grid.py
> +    assert grid.traverse(dummy_scorer, {}, plan, 1, 0, 3, recorder) is None
feel a bit yucky that I am relying on the state of an object that is not obviously in scope of the function. Would much prefer to return the "record". But I don't intend to fix. So this is just a reminder that this work was pretty quick and dirty. I don't want people to think that docstrings == good code 😬

2023-09-08 14:04 UTC, fredshone commented on tests/test_27_optimise_random.py
> +        assert stopper.stop(1) is False
Prefer readable in this case

2023-09-08 15:46 UTC, fredshone commented
@brynpickering all done I promise - sorry for delay - completed minced the history 🍔

2023-09-08 16:11 UTC, brynpickering approved these changes
Since this PR was mostly to introduce docs updates and those look good, let's merge it in! 

I reimplemented your ref to the favicon. It doesn't require a special .ico file (see my additions to `mkdocs.yml`)

2023-09-08 16:25 UTC, merged