location model for discretionary activities
arup-group/pam pull request #252
Opened 2023-09-13 16:53 UTC by Theodore-Chatziioannou

This PR applies a time-prism approach for choosing the location of non-mandatory activities. With this approach, agents try to sensibly combine the location of their discretionary activities around the locations of “anchor points” (defined as the locations of mandatory activities – home, employment, education).

The pam.planner.choice_location.DiscretionaryTrips class allows the user to apply the time-space prism approach on a PAM plan, given accessibility and attraction data.

The typical workflow goes as follows:
```
model = DiscretionaryTrips(population, od) # initialize the model and point to the data objects 
model.update_plan() # apply the model and update the location of each non-mandatory activity in the plan
```

We start by identifying fixed mandatory locations (ie home, work, education), splitting the PAM plan into chains of activities.

We then distinguish between 4 possible cases of trip chains:

![example-discretionary-cases](https://github.com/arup-group/pam/assets/60702999/1032c397-8ec3-4af8-9647-99971ef61ef1)

Case 1 is a simple tour between mandatory activities, and may be approached with a discrete choice model (see 15_advanced_choice_modelling.ipynb).

Case 2 selects a possible destination using origin-destination probabilities from the anchor location (saved under the od_probs variable of the od object)

Case 3 weights candidate locations as a function of three elements:

leg ratio, which captures how likely it is for the discretionary location to be closer to the previous or to the next fixed location (between 0 and 1)​
diversion factor, which captures the deviation from the straight path the individual is likely to accept in order to reach a discretionary activity location
attraction (OD probabilities), which captures the number of opportunities in a destination
The final destination probabilities are calculated by multiplying the three elements: 

Case 4 solves the first location as case 2, and then the rest as case 3.

## Checklist

Any checks which are not relevant to the PR can be pre-checked by the PR creator.
All others should be checked by the reviewer(s).
You can add extra checklist items here if required by the PR.

- [ ] CHANGELOG updated
- [ ] Tests added to cover contribution
- [ ] Documentation updated

2023-09-15 10:17 UTC, brynpickering commented
@Theodore-Chatziioannou the code needs linting/formatting. Two options:

Install `pre-commit` in your dev environment: `pre-commit install` 

Then run it on all files: `pre-commit run --all-files`

With pre-commit installed, future commits will be auto-cleaned.

2023-09-15 10:28 UTC, Theodore-Chatziioannou commented
> pre-commit run --all-files

nice - done

2023-09-18 10:36 UTC, brynpickering requested changes
Nicely packaged implementation @Theodore-Chatziioannou ! I have some clean-up and clarification comments. I'll leave @panostsolerid to comment on the value of the implementation itself.

2023-09-18 10:36 UTC, brynpickering commented on tests/conftest.py
Additions here seem like a maintenance nightmare. I have an activity sequence generator that I've put together locally that I'll add to this branch once you've clarified some other comments.

2023-09-18 10:36 UTC, brynpickering commented on tests/conftest.py
> +            end_area="b",
Is "b" the correct end area? The next activity happens in area "c".

2023-09-18 10:36 UTC, brynpickering commented on tests/conftest.py
> +            end_area="a",
Is "a" the correct end area? The next activity happens in area "c".

2023-09-18 10:36 UTC, brynpickering commented on tests/conftest.py
> +            end_area="a",
Is "a" the correct end area? The next activity happens in area "c".

2023-09-18 10:36 UTC, brynpickering commented on tests/test_24_planner_choice_location.py
> +    assert approx(discretionary_trip_od.diversion_p, abs=0.05) == [0.545, 0.545, 0.545]
Should `abs` be `0.005`?

2023-09-18 10:36 UTC, brynpickering commented on tests/test_24_planner_choice_location.py
> +    assert approx(discretionary_trip_od.destination_p, abs=0.005) == [
Should `abs` be the same order of magnitude as the numbers (which are more like `0.00000005`)?

2023-09-18 10:36 UTC, brynpickering commented on tests/conftest.py
> +                np.array([[333, 250, 222], [250, 1000, 250], [222, 250, 333]]),
This was something I noticed in the example notebook. Why are the probabilities > 1? Is this standard for OD matrices?

2023-09-18 10:36 UTC, brynpickering commented on examples/17_advanced_discretionary_locations.ipynb
> +    "logging.basicConfig(level=logging.DEBUG)\n",
Can you try `logging.getLogger('pam').setLevel(logging.DEBUG)` to avoid getting aloads of matplotlib debug logs? If this doesn't work then we should definitely open an issue to create a pam-specific logger that allows users to change the log level for pam-only log messages.

2023-09-18 10:36 UTC, brynpickering commented on examples/17_advanced_discretionary_locations.ipynb
> +    "model._od[\"od_probs\", \"w\", :, \"car\"]"
If you are inspecting a private property in the example notebook, perhaps there should be a public interface to it:

``` python
@property
def od():
    return self._od
```

2023-09-18 10:58 UTC, brynpickering commented on tests/conftest.py
> +        Activity(
activity ends at 5h but next leg starts at 2h

2023-09-18 10:59 UTC, brynpickering commented on tests/conftest.py
> +            end_area="z",
are all shops in this sequence expected to be in "z"?

2023-09-18 10:59 UTC, brynpickering commented on tests/conftest.py
> +            area="b",
should "home" be in area "h"?

2023-09-18 11:01 UTC, brynpickering commented on tests/conftest.py
> +            loc=Point(0, 0),
work is in the same location as home. By design?

2023-09-19 13:40 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +from typing import List, Literal, NamedTuple, Optional, Union
both are valid - I used `List` to keep compatibility with v3.7. I see now that we have dropped support for 3.7 in other places, so I am renaming.

2023-09-19 13:42 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +    def __init__(self, trip_chain: List[Union[Activity, Leg]], od: OD) -> None:
you are right, PEP suggests keeping the docstrings under init. Moved

2023-09-19 13:49 UTC, Theodore-Chatziioannou commented on pam/planner/utils_planner.py
> +def get_act_names(seqs: List[Union[Activity, Leg]]) -> List[str]:
yes, this is quite generic, and can have applications in other future modules within pam.planner

2023-09-19 13:57 UTC, Theodore-Chatziioannou commented on pam/planner/utils_planner.py
> +        act.act = "home"
this step adds an "anchor" to a trip chain that does not have one. Here, we make the simple assumption that a chain starts at home, which is at the same zone as the first activity. This is an edge case really, typically plans should start with a "home" activity.

2023-09-19 14:02 UTC, Theodore-Chatziioannou commented on tests/conftest.py
> +            end_area="b",
updated

2023-09-19 14:06 UTC, Theodore-Chatziioannou commented on tests/conftest.py
> +            end_area="z",
yep. The idea is that the "discretionary planner" will allocate them to a different zone.

2023-09-19 14:09 UTC, Theodore-Chatziioannou commented on tests/conftest.py
a generator sounds good! Indeed the current process is a bit unwieldy, with a lot of data repetition and scope for errors.

2023-09-19 14:56 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +    def pdf_leg_ratio(leg_ratios: np.array, observed_ratio: float) -> np.array:
technically yes, but you are not really expected to provide a list of lists here. Simple array communicates intention better here I believe

2023-09-19 14:58 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +    def choose_destination(self):
good idea - updated

2023-09-19 15:03 UTC, Theodore-Chatziioannou commented on examples/17_advanced_discretionary_locations.ipynb
> +    "model._od[\"od_probs\", \"w\", :, \"car\"]"
updated

2023-09-19 15:12 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +        self.anchor_zone_start = trip_chain[0].location.area
added assertions to the trip chain functions

2023-09-19 15:21 UTC, Theodore-Chatziioannou commented on pam/planner/choice_location.py
> +            assert isinstance(self._trip_chain[0], Activity)
moved to initialisation.

2023-09-19 15:36 UTC, Theodore-Chatziioannou commented on examples/17_advanced_discretionary_locations.ipynb
> +    "logging.basicConfig(level=logging.DEBUG)\n",
thanks, that worked!

2023-09-19 15:39 UTC, Theodore-Chatziioannou commented
thanks @brynpickering , I have updated the PR in light of your comments. The activity generator sounds like a good addition once the PR is merged. Let me know if anything else.

2023-09-19 16:26 UTC, brynpickering approved these changes

2023-09-19 16:28 UTC, merged