Writing matsim XML's - Return the object, not the key in case of a dict
arup-group/pam pull request #48
Opened 2020-11-10 14:28 UTC by gac55

An issue with expected types when writing to Matsim xml.

Output before fix:
```
  <object id="10002061023">
    <attribute class="java.lang.String" name="psex">{10002061023: 'Male'}</attribute>
    <attribute class="java.lang.String" name="page">{10002061023: 40}</attribute>
    <attribute class="java.lang.String" name="pdlicense">{10002061023: 1}</attribute>
    <attribute class="java.lang.String" name="hincome">{10002061023: 4}</attribute>
    <attribute class="java.lang.String" name="hsize">{10002061023: 4}</attribute>
    <attribute class="java.lang.String" name="hid">{10002061023: 640586395095}</attribute>
    <attribute class="java.lang.String" name="subpopulation">{10002061023: 'License'}</attribute>
    <attribute class="java.lang.String" name="source">{10002061023: 'phase-2-tfl'}</attribute>
  </object>
```

Output after fix:
```
<object id="10002061023">
    <attribute class="java.lang.String" name="psex">Male</attribute>
    <attribute class="java.lang.String" name="page">40</attribute>
    <attribute class="java.lang.String" name="pdlicense">1</attribute>
    <attribute class="java.lang.String" name="hincome">4</attribute>
    <attribute class="java.lang.String" name="hsize">4</attribute>
    <attribute class="java.lang.String" name="hid">10002061023</attribute>
    <attribute class="java.lang.String" name="subpopulation">License</attribute>
    <attribute class="java.lang.String" name="source">phase-2-tfl</attribute>
  </object>
```
I don't think this is solved, some more effort needs to go into ensuring types are correct. This should happen further upstream, likely at ingestion. At present, users will likely use the types as inferred by Pandas when reading from csv - as was the case with the example above. 

I present this improvement as an incremental change which should at least make debugging better.

2020-11-10 14:51 UTC, fredshone commented
I don't really like this. Prefer that we make it clearer that everything is forced to string. Which i think is what is roughly expected with writing to xml.

Interested to know how you got dictionaries as attributes? Seems there must have been an issue with the read method?

2020-11-10 15:22 UTC, gac55 commented
yes, something in the read method, but I can't trace. Will continue to explore

2020-11-10 15:26 UTC, mfitz requested changes

2020-11-10 15:26 UTC, mfitz commented on pam/write.py
> +                    attribute_xml.text = str(list(v.values())[0])
I'm a bit surprised this did not cause a test somewhere to break. Presumably that's because we are not using the kind of data in any of the unit tests that would reproduce the bug? With any bug, we should really start with one or more new tests that fail because of the bug and turn green after we've applied the fix, so I think we need at least one new test.

2020-11-10 15:26 UTC, mfitz commented on pam/write.py
> +                    attribute_xml.text = str(list(v.values())[0])
<img width="970" alt="Screen Shot 2020-11-10 at 15 24 18" src="https://user-images.githubusercontent.com/250899/98693983-db6f2f80-2368-11eb-8926-cfa4da713a48.png">

Couple of gaps identified by the coverage report that we should plug with new tests, I think, especially since one of them (line 215) is at the heart of the change in this PR.

2020-11-10 16:20 UTC, gac55 commented
I am unable to create my bug without using the large input Collins gave me. I don't think it's at read anymore, but somewhere in the middle of the pipeline

2020-11-11 14:45 UTC, gac55 commented
This issues was caused by duplicate household rows. This resulted in https://github.com/arup-group/pam/blob/master/pam/read.py#L84 returning a dictionary with nested dictionaries. 

I will close this and open an issue.

2020-11-11 14:45 UTC, closed without merging