Support matsimv 12
arup-group/pam pull request #72
Opened 2021-02-19 18:56 UTC by fredshone

FYI

Adds support for read/write for matsim xml v12 (just add `version = 12`) to the existing matsim read/write methods. Note that default remains 11 so no breaks...

There is no requirement to bump existing pops up to 12 right now (Andrew).

I've also culled the requirements file. Infact the underlying dependancy tree is the same - so no real change i think - just looks nicer. Kasia has suggested removing the jupyter and ipython reqs to save space but because notebooks are the only real use case at the moment i leave in.

Changes are tested pretty well and i added some better doc strings to the write methods.

I made a read/write consistency test for xml v12 so I'm pretty confident it's working, but I've not tested on matsim yet.

A lot of the extra code is to add `__contains__` (eg is `personA in HouseholdA`) and __eq__ (eg is `personA == personB`) to the core module, which then supports the consistency test and i expect to be useful in future. The equalities are agnostic to person and household IDs - they should decend right down into attributes, then child attributes and so on down to plan components. This means that to get a True equality for two big populations will take a long time (i have not tested) but for most use cases where the populations are small or the inequality closer to the parent then it is quick.

2021-02-22 16:54 UTC, fredshone commented
This is updated to also support v11 and v12 matsim route reading.

For now I have opted not top support writting routes back to matsim (though i can see a use case in future).

2021-02-23 00:30 UTC, mfitz requested changes

2021-02-23 00:30 UTC, mfitz commented on tests/test_1_core_operations.py
> +    population = Population()
Is the exception expected because the population is empty, or because we're not passing in a `Person` type?

2021-02-23 00:30 UTC, mfitz commented on tests/test_1_core_operations.py
> +    # same person
Again, I'd go with separate tests here

2021-02-23 00:30 UTC, mfitz commented on tests/test_3_parse_matsim.py
> +        population = read_matsim(test_tripsv12_path, attributes_path='fake', version=12)
Could we make a stronger assertion about what has happened? Maybe assert on the expected message in the exception, or possibly use a custom exception?

2021-02-23 00:30 UTC, mfitz commented on tests/test_8_write.py
>  def test_write_plans_xml(tmp_path, population_heh):
I think there are a couple of tests missing here:

1 - Test XML file created is valid against the DTD (grab a local copy of the [DTD](https://www.matsim.org/files/dtd/population_v6.dtd), see [here](https://github.com/arup-group/genet/blob/master/tests/test_outputs_handler_matsim_xml_writer.py#L44) for an example of how to perform the validation)

2 - Test XML file has the expected content, based on the population we've used to create it

2021-02-23 00:30 UTC, mfitz commented on tests/test_8_write.py
>      # TODO make assertions about the content of the created file
Yes, that would be nice :-P

2021-02-23 00:30 UTC, mfitz commented on tests/test_8_write.py
> +    write_matsim_plans(population_heh, path=plans_location, comment="test")
Could you use your new population equality function in the assertion for the round trip serialisation/deserialisation here?

2021-02-23 00:30 UTC, mfitz commented on tests/test_8_write.py
> +    # TODO make assertions about the content of the created file
Same comment as before - tests for XML validity and then content would be handy

2021-02-23 00:30 UTC, mfitz commented on tests/test_8_write.py
> +    # TODO make assertions about the content of the created file
Here we should maybe check it's a valid gzip file?

2021-02-23 09:16 UTC, fredshone commented on pam/write.py
> +            # person.attributes["hid"] = hid  # force add hid as an attribute
Thanks for the reminder. I've now made adding the household key to person attributes a default behaviour for both v11 and v12. 

This is maybe useful in future so that we can recover hh attributes from matsim populations (we currently don't use a household representation in matsim).

2021-02-23 10:36 UTC, fredshone commented on tests/test_1_core_operations.py
> +    assert hh2 in population
yes I know :( I have split them up.

2021-02-23 10:38 UTC, fredshone commented on tests/test_1_core_operations.py
> +    population = Population()
...because not passing person type. This seems broadly in line with python although not very safe.

2021-02-23 10:38 UTC, fredshone commented on tests/test_1_core_operations.py
> +    # same person
yes

2021-02-23 10:40 UTC, fredshone commented on tests/test_3_parse_matsim.py
> +        population = read_matsim(test_tripsv12_path, attributes_path='fake', version=12)
I agree - but i think this will be premature optimisation at present.

2021-02-23 17:24 UTC, fredshone commented on tests/test_8_write.py
>  def test_write_plans_xml(tmp_path, population_heh):
added

2021-02-23 17:25 UTC, fredshone commented on tests/test_8_write.py
> +    # TODO make assertions about the content of the created file
you are right but maybe next time

2021-02-23 17:27 UTC, fredshone commented on tests/test_8_write.py
> +    # TODO make assertions about the content of the created file
i think this is covered ok by read write continuity tests

2021-02-23 17:47 UTC, fredshone commented on tests/test_8_write.py
> +    # TODO make assertions about the content of the created file
done

2021-02-23 18:44 UTC, fredshone commented on tests/test_1_core_operations.py
> +    # same person
done

2021-02-24 12:43 UTC, mfitz approved these changes

2021-02-24 13:48 UTC, merged